// <auto-generated />
using System;
using BookShelfAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookShelfAPI.Migrations
{
    [DbContext(typeof(BookShelfContext))]
    [Migration("20260309131307_InitialCreatePostgres")]
    partial class InitialCreatePostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookShelfAPI.Models.CalendarioMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeLivros")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("CalendariosMensais");
                });

            modelBuilder.Entity("BookShelfAPI.Models.DesafioAZ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "Ano")
                        .IsUnique();

                    b.ToTable("DesafiosAZ");
                });

            modelBuilder.Entity("BookShelfAPI.Models.LetraDesafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completado")
                        .HasColumnType("boolean");

                    b.Property<int>("DesafioAZId")
                        .HasColumnType("integer");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("TituloLivro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DesafioAZId");

                    b.ToTable("LetrasDesafio");
                });

            modelBuilder.Entity("BookShelfAPI.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Coracoes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estrelas")
                        .HasColumnType("integer");

                    b.Property<bool>("Favoarito")
                        .HasColumnType("boolean");

                    b.Property<int>("Fogos")
                        .HasColumnType("integer");

                    b.Property<string>("Genero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Humor")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TempoDeLeiturasDias")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("BookShelfAPI.Models.MetaLeitura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeLida")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeObjetivo")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "Ano")
                        .IsUnique();

                    b.ToTable("MetasLeitura");
                });

            modelBuilder.Entity("BookShelfAPI.Models.MetaLeituraLivro", b =>
                {
                    b.Property<int>("MetaLeituraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LivroId")
                        .HasColumnType("integer");

                    b.HasKey("MetaLeituraId");

                    b.HasIndex("LivroId");

                    b.ToTable("MetaLeituraLivros");
                });

            modelBuilder.Entity("BookShelfAPI.Models.ProximoLeitura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ProximasLeituras");
                });

            modelBuilder.Entity("BookShelfAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BookShelfAPI.Models.CalendarioMensal", b =>
                {
                    b.HasOne("BookShelfAPI.Models.Usuario", "Usuario")
                        .WithMany("CalendariosMensais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookShelfAPI.Models.DesafioAZ", b =>
                {
                    b.HasOne("BookShelfAPI.Models.Usuario", "Usuario")
                        .WithOne("DesafioAZ")
                        .HasForeignKey("BookShelfAPI.Models.DesafioAZ", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookShelfAPI.Models.LetraDesafio", b =>
                {
                    b.HasOne("BookShelfAPI.Models.DesafioAZ", "DesafioAZ")
                        .WithMany("Letras")
                        .HasForeignKey("DesafioAZId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesafioAZ");
                });

            modelBuilder.Entity("BookShelfAPI.Models.Livro", b =>
                {
                    b.HasOne("BookShelfAPI.Models.Usuario", "Usuario")
                        .WithMany("Livro")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookShelfAPI.Models.MetaLeitura", b =>
                {
                    b.HasOne("BookShelfAPI.Models.Usuario", "Usuario")
                        .WithOne("MetaLeitura")
                        .HasForeignKey("BookShelfAPI.Models.MetaLeitura", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookShelfAPI.Models.MetaLeituraLivro", b =>
                {
                    b.HasOne("BookShelfAPI.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookShelfAPI.Models.MetaLeitura", "MetaLeitura")
                        .WithMany("LivrosNaMeta")
                        .HasForeignKey("MetaLeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("MetaLeitura");
                });

            modelBuilder.Entity("BookShelfAPI.Models.DesafioAZ", b =>
                {
                    b.Navigation("Letras");
                });

            modelBuilder.Entity("BookShelfAPI.Models.MetaLeitura", b =>
                {
                    b.Navigation("LivrosNaMeta");
                });

            modelBuilder.Entity("BookShelfAPI.Models.Usuario", b =>
                {
                    b.Navigation("CalendariosMensais");

                    b.Navigation("DesafioAZ");

                    b.Navigation("Livro");

                    b.Navigation("MetaLeitura");
                });
#pragma warning restore 612, 618
        }
    }
}
